### ISSUE TITLE
Add sound on note created successfully

### ISSUE THREAD

**Issue by Alcyone713** [GDSC-IGDTUW-Autumn-of-Code-2022/webD-notes-app#4]

**Comment by Nitya-Pasrija** [comment]
Hey @Alcyone713 @Parul-Mann 
Can you assign this to me?

**Comment by iamatifmoin** [comment]
@Alcyone713 
I have resolved the issue. 
The PR can now be merged.

**Comment by aditigahoi** [comment]
@Alcyone713 Please assign this issue to me

**Comment by BhavyaDevani** [comment]
@Alcyone713 @Parul-Mann pls assign this issue to me

**Comment by iamatifmoin** [comment]
@13101182021 resolved already.
