### ISSUE TITLE
Add option to edit note

### ISSUE THREAD

**Issue by Alcyone713** [GDSC-IGDTUW-Autumn-of-Code-2022/webD-notes-app#6]

**Comment by Aakriti-malla** [comment]
Hey! @Alcyone713 I would like to work on this issue and make the changes. Kindly assign me this!

**Comment by aditigahoi** [comment]
@Alcyone713 @Parul-Mann  Please assign this issue to me. I would like to work upon this.

**Comment by ASHWINISHARMABTCSAI118** [comment]
hello!!!! @Alcyone713  kindly assign me on this issue, I would love to work on it !!!
