### ISSUE TITLE
Show toast message on new note created successfully

### ISSUE THREAD

**Issue by Alcyone713** [GDSC-IGDTUW-Autumn-of-Code-2022/webD-notes-app#8]
The toast message should appear at the bottom of the page.

**Comment by 1218muskan** [comment]
I would like to work on this issue. Kindly assign it to me.

**Comment by AasthaSinghal21** [comment]
Hey! I would like to work on this issue. Please assign me this.

**Comment by iamatifmoin** [comment]
@Alcyone713 I have resolved this issue already. 
Please assign me this so I can make a PR.

**Comment by iamatifmoin** [comment]
@Alcyone713 
This is what my implementation looks like -

![issue-8](https://user-images.githubusercontent.com/97212195/201827083-4f6e1df4-a496-4a6e-9868-c0e685e41aa1.png)

**Comment by trushee** [comment]
@Alcyone713 I would like to work on this issue

**Comment by 1218muskan** [comment]
Hey @Alcyone713 , I wasn't aware of the fact that the message should be placed on bottom of the page, so I positioned it in middle. Just the position needs to be changed, I can make changes to my code, this will take only few minutes.

**Comment by iamatifmoin** [comment]
@1218muskan 
I have not made any changes to your code. 
Just fixed the position for you.

**Comment by iamatifmoin** [comment]
@Alcyone713 
This can now be Merged.
